---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started
- name: nginx restart
  service:
    name: nginx
    state: restarted
- name: php-fpm systemd
  systemd:
    name: php7.4-fpm
    enabled: yes
    state: started
